### ISSUE TITLE
Project ideas

### ISSUE THREAD

**Issue by squisty** [UBC-MDS/doggodash#1]
Thread for suggesting topics for our dashboard and linking relevant data sets we could use.

**Comment by stevenleung2018** [comment]
Potential dataset to work with: Dogs: https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-02-01

**Comment by stevenleung2018** [comment]
Per meeting today, we have the consensus to use this dataset for creating the dashboard.
