### ISSUE TITLE
Dash/interactivity

### ISSUE THREAD

**Issue by squisty** [UBC-MDS/doggodash#27]

**Comment by shivajena** [comment]
Test dash implementation first cut.
![Screenshot 2022-03-02 at 11 59 34 AM](https://user-images.githubusercontent.com/68426015/156440708-8d8b6cab-48f1-4945-b256-b55c2b1e6eac.png)

**Comment by shivajena** [comment]
- [x] Added different weights for likeable and dislikeable traits, which works as input for the weights in the results
- [x] Changed the layout and sizing options and added interactivity.
- [x] Dog images can also be seen now by clicking on the results (bar plot)

![sketch](https://user-images.githubusercontent.com/68426015/156849945-dac5e7ea-1491-4342-b16e-0e6a561ebcaa.png)
![sketch2](https://user-images.githubusercontent.com/68426015/156849954-5b1bee1d-e43f-4825-83e2-89ac2d59607d.png)
