### ISSUE TITLE
Add favicon + title to app

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/doggodash#42]
<img width="781" alt="Screen Shot 2022-03-07 at 2 48 54 PM" src="https://user-images.githubusercontent.com/94651544/157131142-5d3c68b7-eab8-447b-b654-1628ff37b9ad.png">

**Comment by shivajena** [comment]
- [x] Add favicon
- [ ] Add title

**Comment by shivajena** [comment]
This is done. Can go ahead for merging PR #48
