### ISSUE TITLE
Compare technologies

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/doggodash#44]
Repo: https://github.com/UBC-MDS/dash-tableau-shiny_comparison

Assignment: DASH's Documentation and reproducibility

1. Mention all the official documentation resources. 
2. Are there ways to run the dashboard in a reproducible way locally (ie., creating a package?, Docker? Binder? Nothing is said about it?) Provide links/examples if you find that it is possible.

**Comment by stevenleung2018** [comment]
@gn385x @squisty @shivajena Hi team, this task is done.  Please feel free to review.  https://github.com/stevenleung2018/dash-tableau-shiny_comparison/blob/main/group_18.md
If all good, I will generate a PR to the main repo (mine being a forked repo) as a way to submit.

**Comment by stevenleung2018** [comment]
Here is the PR to the main repo:

https://github.com/UBC-MDS/dash-tableau-shiny_comparison/pull/3
