### ISSUE TITLE
Peer review for group 19 - Back-end & Documentation

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/doggodash#45]
Instructions: https://github.com/UBC-MDS/DSCI532-peer-review

<img width="843" alt="Screen Shot 2022-03-07 at 3 26 25 PM" src="https://user-images.githubusercontent.com/94651544/157135338-a3561baa-68e2-4a94-ada7-d189e3e9c566.png">

**Comment by shivajena** [comment]
**Backend**

-   Are the options that you can select in the widgets working fine or have you found some cases where it is not working?

    -   There are 3 widgets - country, salary range and answer to the question - Are you a data scientist. The widgets are working fine.

-   If there are interactive plots: are the labels clear and easy to understand?

    -   All the labels are clear and easy to understand

    -   The right side bottom panel just needs to be size optimised to fit in a 100 % view browser, or may be a scroll option could be introduced by enabling autoscroll in the respective container.

**Documentation**

-   Was the documentation easy to understand from the `README.md` how to use the app? How could the documentation be improved?

    -   Yes, the documentation is succinct and clear.

    -   I dont think there is much room for improvement here, as it is quite clear in terms of stating objective, data source, image of dashboard etc..

-   Was the app intuitive to use without reading the documentation? What information could be good to include?

    -   Yes, the app is quite self explanatory.

    -   While the world map is quite informative, Including a top 5 countries list in terms of average pay per unit experience can be a great takeaway.

**Indicate something you would like to include in your own app after reviewing this one**

-   Our app is a minimalist app in the sense that it is designed specifically to reduce confusion in the minds of the dog owners (doggodash).

-   Therefore, I dont see any particular takeaway that can be applied to our dashboard

**Comment by shivajena** [comment]
- [x] back end
- [x] Documentation
- [x] App takeaways to implement in our dashboard
